apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://localhost:9090 # Local prometheus installation for now
    #url: http://prometheus:9090 # assumes Prometheus runs in Docker under service name 'prometheus'. If run locally, switch to 'http://localhost:9090'
    isDefault: true
    editable: false