
help:
	@echo "Available commands:"
	@grep -hE '^[a-zA-Z0-9_-]+:.*##' makefiles/*.mk | \
		awk 'BEGIN {FS = ":.*##"}; {printf "  %-20s %s\n", $$1, $$2}'

# ---------------------------------------------------------
# HELP
# ---------------------------------------------------------
# help:
# 	@echo "Available commands:"
# 	@echo ""
# 	@echo "  make install           - Install project in editable mode"
# 	@echo ""
# 	@echo "  make server-status     - Check MLLP server status"
# 	@echo "  make run-server        - Run MLLP server that hosts listener"
# 	@echo "  make restart-server    - Restart MLLP server that hosts listener"
# 	@echo "  make kill-own-server   - Kill own HL7 MLLP server if still running (safer)"
# 	@echo "  make kill-server       - Kill any running HL7 MLLP server"
# 	@echo "  make run-ui            - Run UI server to view HL7 messages"
# 	@echo ""
# 	@echo "  make test              - Run full test suite"
# 	@echo "  make test-file FILE=…  - Run a specific test file"
# 	@echo "  make test-name NAME=…  - Run a specific test by name"
# 	@echo "  make benchmark-tests   - Show slowest tests"
# 	@echo "  make coverage          - Run coverage report"
# 	@echo ""
# 	@echo "  make bench-max         - Max throughput benchmark"
# 	@echo "  make bench-conn        - Connection-only stress test"
# 	@echo "  make bench-sweep       - Concurrency sweep"
# 	@echo "  make bench-visualize FILE=…"
# 	@echo "                         - Visualize a benchmark JSON file"
# 	@echo "  make run-benchmark     - Run any benchmark against a temporary server instance. Usage:"
# 	@echo "                             + make run-benchmark BENCHMARK=--sweep"
# 	@echo "                             + make run-benchmark BENCHMARK=--conn-stress DURATION=30"
# 	@echo "                             + make run-benchmark BENCHMARK=--max-throughput EXTRA=\"--warmup 5\""
# 	@echo ""
# 	@echo "  make clean-db          - Remove SQLite DB"
# 	@echo "  make clean-routed      - Remove routed HL7 files"
# 	@echo "  make clean-results     - Remove results JSON files"
# 	@echo "  make reset             - Clean DB and routed + results folders"
# 	@echo ""
# 	@echo "  make prometheus        - Start Prometheus service as configured in PROM_CONFIG"
# 	@echo "  make prometheus-bg     - Start Prometheus service in background"
# 	@echo "  make prometheus-status - Show Prometheus server status"
# 	@echo "  make restart-prometheus - Restart Prometheus server"
# 	@echo "  make prometheus-test   - Curl /metrics to verify Prometheus endpoint"
# 	@echo "  make kill-prometheus   - Stop Prometheus server"
# 	@echo ""
# 	@echo "  make grafana           - Start Grafana server in foreground"
# 	@echo "  make grafana-bg        - Start Grafana server in background"
# 	@echo "  make kill-grafana      - Stop Grafana server"
# 	@echo "  make restart-grafana   - Restart Grafana server"
# 	@echo "  make grafana-status    - Show Grafana server status"
# 	@echo ""
# 	@echo "  make server-status-all - Show status of HL7 engine, REST API, Prometheus, Grafana"
# 	@echo "  make monitoring-stack  - Start Prometheus, Grafana and MLLP server (HL7 engine) with Prometheus enabled"
# 	@echo "  make monitoring-logs   - Show logs for Prometheus and Grafana"
# 	@echo "  make kill-monitoring   - Stop HL7 MLLP server, Prometheus + Grafana"